### ISSUE TITLE
Where can I find those 27 questions the paper mentioned?

### ISSUE THREAD

**Issue by St0neWan9** [UditGupta10/GPT-InvestAR#1]
While I read the paper, noticed that you guys use 27 questions for LLM to extract features and scores, and the source code have a question.json which have just one question in the file.

So, could you help where can I find those questions for studying?

**Comment by UditGupta10** [comment]
The exact question prompts for all the 27 features are not publicly available. But, they are not hard to figure out either. They are based on questions regarding the fundamental data of the company's performance.
Some insights can be obtained from the feature columns as shown in the train set here: https://github.com/UditGupta10/GPT-InvestAR/blob/main/modeling_and_return_estimation.ipynb

**Comment by UditGupta10** [comment]
They have now been updated. Kindly check the latest commits.
