### ISSUE TITLE
about pd.qcut()

### ISSUE THREAD

**Issue by PzySeere** [UditGupta10/GPT-InvestAR#3]
In this part, I got a error:
<img width="848" alt="image" src="https://github.com/UditGupta10/GPT-InvestAR/assets/70280020/67cc99c5-4fed-4737-9969-5bf4e9701e88">
<img width="776" alt="image" src="https://github.com/UditGupta10/GPT-InvestAR/assets/70280020/c963e77c-a34b-4062-9c08-e41dbc6ef30b">
If it means the codes need change a little bit to avoid the duplicated bin edges? Did u meet this error before? Thanks so much for your reply in advance !

**Comment by UditGupta10** [comment]
Most likely you are passing input data with lots of duplicates. Check that:
1. This function is being applied to each era separately.
2. The 'input_col' is a continuous value and not discrete with lots of duplicated values.
3. Refer: https://github.com/UditGupta10/GPT-InvestAR/blob/b3ed792cd6736033d8c9da604637e44d211e33c6/make_targets.py#L210

**Comment by PzySeere** [comment]
> Most likely you are passing input data with lots of duplicates. Check that:
> 
> 1. This function is being applied to each era separately.
> 2. The 'input_col' is a continuous value and not discrete with lots of duplicated values.
> 3. Refer: https://github.com/UditGupta10/GPT-InvestAR/blob/b3ed792cd6736033d8c9da604637e44d211e33c6/make_targets.py#L210

Thanks for your explain! I just found that , the issue is because for a era such as 2002, it may only has one stock data, so the bin_targets cannot do the pd.qcut().  

To summary, if anyone want to test the codes with small datasets which only has several stocks. It may occur this problem.
