### ISSUE TITLE
Error in  gpt_scores_as_features.py

### ISSUE THREAD

**Issue by MingyuJ666** [UditGupta10/GPT-InvestAR#4]
In gpt_scores_as_features.py, line80.
ValueError: Must provide a LangChainLLM.

<img width="1440" alt="截屏2023-09-16 18 18 16" src="https://github.com/UditGupta10/GPT-InvestAR/assets/124435499/3e3234c7-e5aa-490e-a8e8-ab06eafcca10">

**Comment by UditGupta10** [comment]
Please provide a dump of the complete error log. Line number 80 is empty in the code.

**Comment by MingyuJ666** [comment]
<img width="701" alt="截屏2023-09-17 11 31 00" src="https://github.com/UditGupta10/GPT-InvestAR/assets/124435499/6042a04c-d28b-4d8f-b0c2-9951b48834cb">

**Comment by UditGupta10** [comment]
Please check if you have installed all packages with the correct versions: https://github.com/UditGupta10/GPT-InvestAR/blob/main/requirements.txt
I would suggest using anaconda.
I am able to run the code at my end. In absence of a complete error log, it's tricky to help.

**Comment by MingyuJ666** [comment]
In line 82, he said TypeError: eval() arg 1 must be a string, bytes or code object
<img width="772" alt="截屏2023-09-17 13 50 58" src="https://github.com/UditGupta10/GPT-InvestAR/assets/124435499/400cff35-cdc6-4e1e-877a-d64db288f261">
<img width="879" alt="截屏2023-09-17 13 50 36" src="https://github.com/UditGupta10/GPT-InvestAR/assets/124435499/6d1ee7a2-bad0-46a1-a08a-1dbfe27ff0aa">

**Comment by UditGupta10** [comment]
@jmyissb I'll advise you to run these step by step in a Jupyter notebook.
The error you are facing here is because the response from the LLM cannot be converted to int type or isn't in the desired format.

**Comment by MingyuJ666** [comment]
<img width="418" alt="截屏2023-09-18 14 02 37" src="https://github.com/UditGupta10/GPT-InvestAR/assets/124435499/1f132f90-c012-4315-85f2-ad25857b949f">
why my feature is always 0

**Comment by MingyuJ666** [comment]
how to extract text when we ask gpt in gpt_scores_as_features.py I want to know what you send to chatgpt

**Comment by MingyuJ666** [comment]
By the way, how to see the context information in the template

**Comment by UditGupta10** [comment]
https://github.com/UditGupta10/GPT-InvestAR/issues/5#issuecomment-1722777289

**Comment by MingyuJ666** [comment]
I mean what part of the pdf of financial report we use

**Comment by MingyuJ666** [comment]
I ask the question and send a part of the financial report to gpt. how can I see the part of the report

**Comment by UditGupta10** [comment]
The original issue is resolved. Marking it resolved.

**Comment by MingyuJ666** [comment]
You can see the template, I want to know what the context is. 
![image](https://github.com/UditGupta10/GPT-InvestAR/assets/124435499/5cf5b4b0-449d-4742-bb30-2de4b01f5b94)
