### ISSUE TITLE
Template to create the questions

### ISSUE THREAD

**Issue by PzySeere** [UditGupta10/GPT-InvestAR#5]
I tried some questions such as: "profit": "Does the company got a good profit in this year? Does the company do good in this year?"
But the llm give me the answer is not '0.8' something like that. It give me {"score":"Yes"}.
Is there any tips to makesure the questions will get a value answer not "Yes", "No", "Uncertain". Thanks so much!

**Comment by jmyissb** [comment]
do you know what do things they throw to gpt, text? or embedding vector?

**Comment by UditGupta10** [comment]
@PzySeere Prompt Engineering is an important aspect of this exercise and I would suggest to spend some time learning how to create the best prompts to get the desired response from an LLM.

For this specific case, one of the options can be:
1. Always give your response in dictionary format: {key: value}. Here the key is always set to the string 'score' and the value is the your answer to the asked question. The value should be an integer in the range 0 to 100.

This is a prompt which is likely to give you the answer in desired format. Is it the best prompt for the problem at hand? Possibly no.
