### ISSUE TITLE
Does GPT-InvestAR support to use Azure OpenAI?

### ISSUE THREAD

**Issue by wingtsai** [UditGupta10/GPT-InvestAR#6]
Does GPT-InvestAR support to use Azure OpenAI?

**Comment by UditGupta10** [comment]
An API key is required to access OpenAI models. This can be done on any device without strict hardware requirements.
I've personally not used Azure's OpenAI service but they would also require the OpenAI key (either they manage it for you in exchange for a fee or you provide it on your own) for access.
