### ISSUE TITLE
Issue with the CONFIG_PATH in download_10k.py

### ISSUE THREAD

**Issue by sstephen23** [UditGupta10/GPT-InvestAR#7]
Hi Udit, 

I have followed the readme dependencies notes but when trying to run I am coming up against an error which reads:

usage: ipykernel_launcher.py [-h] --config_path CONFIG_PATH
ipykernel_launcher.py: error: the following arguments are required: --config_path

Any help appreciated.

Thank you

**Comment by UditGupta10** [comment]
The path of config.json (https://github.com/UditGupta10/GPT-InvestAR/blob/main/config.json) must be provided  in the script.
