### ISSUE TITLE
Can't find the 27 dimensions question list

### ISSUE THREAD

**Issue by Li-Evan** [UditGupta10/GPT-InvestAR#9]
Hi, I recently had the opportunity to read your paper and found it to be incredibly insightful and thought-provoking. However, I noticed in your paper you referenced a comprehensive list of questions encompassing 27 dimensions. We are very keen to delve deeper into your research, but upon reviewing the materials on your GitHub, it appears that only a portion of this list is available. (exactly in question.json)

Would it be possible for you to share the complete list of questions? Having access to this information would greatly assist us in fully understanding and potentially replicating your study.

Thank you in advance for your time and assistance. Your work is greatly appreciated and we are looking forward to exploring it further.

**Comment by UditGupta10** [comment]
I understand that having the exact questions used would be beneficial, however due to the dynamic nature of LLMs, replicability will still be tricky. There has been a lot of interest around this subject. Please have a look at the discussions here and let me know if it suffices: https://github.com/UditGupta10/GPT-InvestAR/issues?q=is%3Aissue+is%3Aclosed

**Comment by Li-Evan** [comment]
I understand that large language models can sometimes produce unstable outputs. I've reviewed similar queries from others and also looked through the 'modeling_and_return_estimation.ipynb' file as you suggested. Unfortunately, I couldn't find information related to this issue in the file. Could you kindly provide information about the 27 dimensions you mentioned? The specific details of the problem aren't necessary; I'm just interested in understanding the relevant dimensions."

**Comment by UditGupta10** [comment]
They have now been updated. Kindly check the latest commits.
